# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8a5ae37adcbc52f9d8323dd42f55db11ff28d3ae606f2d0ed5bc4def048e668979353e58f31fa932c405fc96b8420ea3b3c5d0fb04f6f756a7a39fd5d75b25a

test:
  secret_key_base: b47906bf4c2e52d590105e3b1186c61c98b29a480e6181531cf15699fa19673e7c9413f4508898f2f1b6f3524efa9f3922a3c7ab53484d27c5f71143ebf746a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
